# -*- coding: utf-8 -*-
"""Frozen closed-registry CAS reference used only for Validation V2 QC.

Purpose
-------
This module lets the open-set chemical-group builder check whether an external
candidate CAS is already directly enumerated in the regulatory closed registry.
It is intentionally kept inside validation_v2 so benchmark construction does
not depend on files generated by earlier experiments.

Source
------
Korea, Designation of Restricted/Prohibited Substances, Annex 3,
Ministry notice No. 2025-28, effective 2026-01-01.
"""

SOURCE_VERSION = "기후에너지환경부고시 제2025-28호, 시행 2026-01-01"

OFFICIAL_CAS_BY_RULE = {
    "MG_SALTS": {
        "10309-95-2", "61725-50-6", "68083-41-0", "569-64-2",
        "2437-29-8", "18015-76-4",
    },
    "TBT_TRIALKYLTIN": {
        "4782-29-0", "1067-97-6", "4342-30-7", "56-35-9",
        "1461-22-9", "1983-10-4", "688-73-3", "3090-36-6",
        "4027-18-3", "2155-70-6", "67772-01-4", "31732-71-5",
    },
    "NONYLPHENOL_NPE": {
        "25154-52-3", "104-40-5", "84852-15-3", "139-84-4",
        "136-83-4", "9016-45-9", "90481-04-2", "11066-49-2",
        "27177-05-5", "68412-54-4", "68412-53-3", "37205-87-1",
        "26027-38-3", "127087-87-0",
    },
    "LEAD_COMPOUNDS": {
        "7439-92-1", "12656-85-8", "1344-37-2", "12578-12-0",
        "91031-62-8", "15245-44-0", "301-08-6", "301-04-2",
        "1335-32-6", "13424-46-9", "13814-96-5", "7758-97-6",
        "10099-74-8", "1317-36-8", "1314-41-6", "12141-20-7",
        "12202-17-4", "1072-35-1", "52732-72-6", "12065-90-6",
    },
    "CRVI_COMPOUNDS": {
        "7788-98-9", "24613-89-6", "1333-82-0", "14977-61-8",
        "13548-42-0", "13530-68-2", "7758-97-6", "14307-35-8",
        "13423-61-5", "16037-50-6", "7789-09-5", "7789-00-6",
        "7778-50-9", "7775-11-3", "10588-01-9", "7789-06-2",
        "13530-65-9", "14018-95-2", "10294-40-3", "13765-19-0",
        "14307-33-6", "12656-85-8", "37300-23-5", "1624-02-8",
        "20039-37-6", "7738-94-5", "13455-25-9", "18540-29-9",
        "13454-78-9", "34493-01-1", "10294-52-7", "12433-50-0",
        "13446-73-6", "13473-75-1", "13453-35-5", "11119-70-3",
        "18454-12-1", "7789-01-7", "7789-10-8", "14721-18-7",
        "15586-38-6", "1344-37-2", "11103-86-9", "41189-36-0",
        "7784-01-2", "7784-02-3", "10034-82-9", "7789-12-0",
        "49663-84-5",
    },
}


def is_directly_enumerated(rule_id: str, cas: str) -> bool:
    return str(cas).strip() in OFFICIAL_CAS_BY_RULE.get(str(rule_id).strip(), set())


def registry_counts() -> dict[str, int]:
    return {k: len(v) for k, v in OFFICIAL_CAS_BY_RULE.items()}


def total_registry_rows() -> int:
    return sum(registry_counts().values())
